import { runTimeWorkflows } from "@/lib/automation";
import { prisma } from "@/lib/db";
import { scheduledDateFor, currentPeriod } from "@/lib/social";
import { getSetting, setSetting } from "@/lib/nuport-sync";
import { sendBulkSMS, normalizeBDNumber } from "@/lib/sms";

// Daily scheduler endpoint. Vercel Cron (or any external cron) calls this once a
// day to fire the time-based automations (birthday, win-back) AND social-media
// metrics reminders — guaranteed even if nobody opens the app.
//
// Security: if CRON_SECRET is set, the caller must send
//   Authorization: Bearer <CRON_SECRET>
// Vercel Cron automatically sends this header when CRON_SECRET is configured.
export async function GET(req: Request): Promise<Response> {
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get("authorization");
    if (auth !== `Bearer ${secret}`) {
      return new Response("Unauthorized", { status: 401 });
    }
  }

  try {
    // 1. Run existing automation workflows
    const workflowResult = await runTimeWorkflows(true);

    // 2. Social media metrics reminders (3 days after posting)
    const threeDaysAgo = new Date(Date.now() - 3 * 86_400_000);
    const reminderResult = await prisma.socialPost.updateMany({
      where: {
        status: "POSTED",
        postedAt: { lte: threeDaysAgo },
        metricsReminderSentAt: null,
      },
      data: { metricsReminderSentAt: new Date() },
    });

    // 3. Auto-generate next month's social plan from templates (runs on the 25th)
    const today = new Date();
    let autoGenerated = 0;
    if (today.getDate() === 25) {
      const nextMonthDate = new Date(today.getFullYear(), today.getMonth() + 1, 1);
      const nextPeriod = `${nextMonthDate.getFullYear()}-${String(nextMonthDate.getMonth() + 1).padStart(2, "0")}`;

      const templates = await prisma.socialTemplate.findMany({ where: { active: true } });
      const existing = await prisma.socialPost.findMany({
        where: { period: nextPeriod, templateId: { not: null } },
        select: { templateId: true },
      });
      const existingIds = new Set(existing.map((p) => p.templateId));
      const toCreate = templates.filter((t) => !existingIds.has(t.id));

      if (toCreate.length > 0) {
        await prisma.socialPost.createMany({
          data: toCreate.map((t) => ({
            templateId:   t.id,
            channel:      t.channel,
            topic:        t.topic,
            notes:        t.notes,
            period:       nextPeriod,
            scheduledDate: scheduledDateFor(nextPeriod, t.dayOfMonth),
            assignedToId: t.assignedToId,
            status:       "PLANNED" as const,
          })),
        });
        autoGenerated = toCreate.length;
      }
    }

    // 4. GMB review SMS — customers purchased exactly 3 days ago
    let reviewSmsSent = 0;
    const gmbUrl      = await getSetting("gmb_review_url");
    const gmbTemplate = await getSetting("gmb_review_message") ??
      "Hi {name}, thank you for your purchase! We'd love your feedback — please leave us a quick Google review: {url} 🙏";

    if (gmbUrl) {
      const windowStart = new Date(Date.now() - 4 * 86_400_000); // 4 days ago
      const windowEnd   = new Date(Date.now() - 3 * 86_400_000); // 3 days ago

      const due = await prisma.customer.findMany({
        where: {
          purchasedAt:     { gte: windowStart, lte: windowEnd },
          reviewSmsSentAt: null,
          whatsappNumber:  { not: null },
        },
        select: { id: true, name: true, whatsappNumber: true },
      });

      if (due.length > 0) {
        const recipients = due
          .filter((c) => c.whatsappNumber)
          .map((c) => ({
            number:  normalizeBDNumber(c.whatsappNumber!),
            message: gmbTemplate
              .replace(/\{name\}/g, c.name)
              .replace(/\{url\}/g,  gmbUrl),
          }));

        const smsResult = await sendBulkSMS(recipients);

        if (smsResult.ok) {
          await prisma.customer.updateMany({
            where: { id: { in: due.map((c) => c.id) } },
            data:  { reviewSmsSentAt: new Date() },
          });
          reviewSmsSent = smsResult.submitted;
        }
      }
    }

    return Response.json({
      ok: true,
      automationActions: workflowResult.actions,
      metricsReminders: reminderResult.count,
      socialPostsGenerated: autoGenerated,
      reviewSmsSent,
      ranAt: new Date().toISOString(),
    });
  } catch (e) {
    console.error("Cron run-automations failed:", e);
    return Response.json(
      { ok: false, error: e instanceof Error ? e.message : "Unknown error" },
      { status: 500 },
    );
  }
}
